<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>MakeNSIS Log</string>

	<key>comment</key>
	<string>https://github.com/idleberg/vscode-nsis</string>

	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^\s*(!error:|Error in script|Error: warning treated as error).*$</string>
			<key>name</key>
			<string>invalid.illegal</string>
		</dict>

		<dict>
			<key>match</key>
			<string>^\s*warning:.*$</string>
			<key>name</key>
			<string>markup.bold</string>
		</dict>
	</array>

	<key>scopeName</key>
	<string>source.makensis</string>

	<key>uuid</key>
	<string>123e4567-e89b-12d3-a456-426614174000</string>
</dict>
</plist>
