<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>nlf</string>
        <string>NLF</string>
    </array>
    <key>name</key>
    <string>NSIS Language File</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
            <string>^\s*#.*$\n?</string>
            <key>name</key>
            <string>comment.line.number-sign.nlf</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
            <key>name</key>
            <string>constant.numeric.nlf</string>
        </dict>
        <dict>
            <!-- $_CLICK -->
            <key>match</key>
            <string>(?i)\$_CLICK</string>
            <key>name</key>
            <string>variable.language.nlf</string>
        </dict>
        <dict>
            <!-- $variable -->
            <key>match</key>
            <string>\$\w+</string>
            <key>name</key>
            <string>variable.other.nlf</string>
        </dict>
        <dict>
            <!-- %s -->
            <key>match</key>
            <string>\%\w+</string>
            <key>name</key>
            <string>constant.language.nlf</string>
        </dict>
        <dict>
            <!-- P&ress key -->
            <key>match</key>
            <string>(\w*?&amp;\w+)</string>
            <key>name</key>
            <string>constant.language.nlf</string>
        </dict>
        <dict>
            <!-- $(^NameDA) -->
            <key>match</key>
            <string>\$\([\w\.:\^-]+\)</string>
            <key>name</key>
            <string>constant.other.nlf</string>
        </dict>
        <dict>
            <!-- \n \r \t -->
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>constant.character.escape.nlf</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.nlf</string>
    <key>uuid</key>
    <string>146caef4-b46e-42e6-960e-2d7cc5e8817a</string>
</dict>
</plist>
